// <auto-generated />
using System;
using AlertaSaneamento.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlertaSaneamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509212648_Localizacao_Atualizacao")]
    partial class Localizacao_Atualizacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlertaSaneamento.Models.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("imagem")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("imagemTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("relato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("AlertaSaneamento.Models.Entities.Atualizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FiscalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("FiscalId");

                    b.ToTable("Atualizacoes");
                });

            modelBuilder.Entity("AlertaSaneamento.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AlertaSaneamento.Models.Entities.Alerta", b =>
                {
                    b.HasOne("AlertaSaneamento.Models.Entities.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AlertaSaneamento.Models.Entities.Atualizacao", b =>
                {
                    b.HasOne("AlertaSaneamento.Models.Entities.Alerta", "Alerta")
                        .WithMany("Atualizacoes")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlertaSaneamento.Models.Entities.Usuario", "Fiscal")
                        .WithMany("Atualizacoes")
                        .HasForeignKey("FiscalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Fiscal");
                });

            modelBuilder.Entity("AlertaSaneamento.Models.Entities.Alerta", b =>
                {
                    b.Navigation("Atualizacoes");
                });

            modelBuilder.Entity("AlertaSaneamento.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Atualizacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
